version: 2
jobs:
  build:
    working_directory: ~/circle
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
      - store_artifacts:
          path: ./artifacts
          prefix: artifacts
      - store_test_results:
          path: ./artifacts/tests
      - run:
          name: upload-coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy:
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: make deploy
  publish:
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
